name: wallet_box
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.2
  flutter_holo_date_picker: ^1.0.6
  fl_chart: ^0.55.1
  percent_indicator: 4.2.2

  http: ^0.13.5
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  mask_text_input_formatter: ^2.4.0
  provider: ^6.0.3
  local_auth: ^2.1.1
  flutter_secure_storage: 5.0.2
  random_password_generator: 0.2.1
  yandex_mapkit: 2.0.1
  # google_language_fonts: ^2.0.0
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  flutter_slidable: ^2.0.0
  animated_theme_switcher: 2.0.6
  fast_barcode_scanner: 1.1.4

  geolocator: ^8.1.1
  google_sign_in: ^5.4.0
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  barcode: ^2.2.1
  barcode_widget: ^2.0.2
  sign_in_with_apple: ^4.1.0
  firebase_auth: ^3.6.2
  crypto: ^3.0.2
  xml2json: ^5.3.4
  xml_parser: ^1.0.0
  #loader_overlay: 2.0.5+1
  logger: ^1.1.0
  screen_loader: ^4.0.1
  flutter_local_notifications: ^9.7.0
  firebase_messaging: ^12.0.1
  app_links: ^3.2.0
  flutter_launcher_icons: ^0.9.3
  home_widget: ^0.1.6
  workmanager: ^0.5.0
  url_launcher: ^6.1.5
  open_file: ^3.2.1
  syncfusion_flutter_datepicker: ^20.2.40

  flutter_share: ^2.0.0
  external_app_launcher: ^3.0.0
  modal_bottom_sheet: ^2.1.0
  image_picker: ^0.8.5+3
  camera: ^0.10.0
  image: ^3.2.0
  flutter_native_image: ^0.0.6+1

  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "lib/app/assets/images/app-icon.png"
  image_path_ios: "lib/app/assets/images/app-icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/app/assets/images/
    - lib/app/assets/icons/