name: wallet_box
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: 2.1.0
  flutter_svg: ^1.0.0
  flutter_holo_date_picker: 1.0.3
  fl_chart: 0.55.0
  percent_indicator: 4.2.2

  http: 0.13.4
  bloc: 8.0.1
  flutter_bloc: 8.0.0
  mask_text_input_formatter: 2.0.0
  provider: 6.0.1
  local_auth: 1.1.9
  flutter_secure_storage: 5.0.2
  random_password_generator: 0.2.1
  yandex_mapkit: 2.0.1
  # google_language_fonts: ^2.0.0
  shared_preferences: 2.0.12
  carousel_slider: 4.0.0
  flutter_slidable: 1.0.0
  animated_theme_switcher: 2.0.6
  fast_barcode_scanner: 1.1.4

  geolocator: ^8.1.1
  google_sign_in: 5.2.4
  firebase_core: ^1.13.1
  firebase_crashlytics: ^2.5.3
  barcode: 2.2.0
  barcode_widget: ^2.0.2
  sign_in_with_apple: ^3.3.0
  firebase_auth: ^3.3.10
  crypto: 3.0.1
  xml2json: ^5.3.2
  xml_parser: ^1.0.0
  #loader_overlay: 2.0.5+1
  logger: 1.0.0
  screen_loader: ^4.0.1
  flutter_local_notifications: ^9.4.0
  firebase_messaging: ^11.2.11
  app_links: 3.0.1
  flutter_launcher_icons: 0.9.2
  home_widget: ^0.1.5
  workmanager: ^0.4.1
  url_launcher: ^6.0.20
  open_file: ^3.2.1
  syncfusion_flutter_datepicker: 20.2.36

  flutter_share: ^2.0.0
  external_app_launcher: ^2.0.2
  modal_bottom_sheet: ^2.0.1
  image_picker: ^0.8.5
  camera: ^0.9.4+20
  image: ^3.1.3
  flutter_native_image: ^0.0.6+1

  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "lib/app/assets/images/app-icon.png"
  image_path_ios: "lib/app/assets/images/app-icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/app/assets/images/
    - lib/app/assets/icons/